/* eslint-disable */
// AUTO-GENERATED by scripts/compile-postal.js — do not edit.
import type { CountryPostalLoader } from './shared/types'

export const countryLoaders: Record<string, CountryPostalLoader> = {
  "US": () => import('./lib/postal-by-country/US.json'),
}

export const countryCodes: string[] = Object.keys(countryLoaders)
